version: '3.8'

services:
  donnum-api:
    build:
      context: ../..
      dockerfile: donor-service/Donnum.DonorService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=DonnumDonorService;User Id=sa;Password=${SQLSERVER_SA_PASSWORD:-Your_password123};TrustServerCertificate=True;
      - Messaging__Broker__HostName=donnum-message-broker
      - Messaging__Broker__Port=5672
      - Messaging__Broker__UserName=${MESSAGING_BROKER_USERNAME}
      - Messaging__Broker__Password=${MESSAGING_BROKER_PASSWORD}
      - Messaging__Broker__ExchangeName=donnum.events
    networks:
      - donnum-shared

networks:
  donnum-shared:
    external: true
    name: donnum-shared
