// <auto-generated />
using System;
using Donnum.DonorService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Donnum.DonorService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260627005933_SeedNewDonorData")]
    partial class SeedNewDonorData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Donnum.BuildingBlocks.Messaging.Abstractions.InboxMessage", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MessageId");

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("Donnum.BuildingBlocks.Messaging.Abstractions.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "NextAttemptAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BadgePoints")
                        .HasColumnType("int");

                    b.Property<int>("BadgeType")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeType")
                        .IsUnique();

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BadgePoints = 50,
                            BadgeType = 2,
                            IsDeleted = false,
                            Name = "Donante Donor"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BadgePoints = 100,
                            BadgeType = 3,
                            IsDeleted = false,
                            Name = "Frecuente"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BadgePoints = 250,
                            BadgeType = 4,
                            IsDeleted = false,
                            Name = "Comprometido"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BadgePoints = 500,
                            BadgeType = 5,
                            IsDeleted = false,
                            Name = "Heroe"
                        });
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.BloodRequestProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("BloodRequestProjections", (string)null);
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DonationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MedicalCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DonationRequestId");

                    b.HasIndex("DonorId");

                    b.HasIndex("MedicalCenterId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0000000-e000-e000-e000-e00000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DonationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DonationRequestId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DonorId = new Guid("d0000000-d000-d000-d000-d00000000001"),
                            IsDeleted = false,
                            MedicalCenterId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.DonationRequestParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonorId", "DonationRequestId")
                        .IsUnique();

                    b.ToTable("DonationRequestParticipations");
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.Donor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("HasGuardianAuthorization")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMedicalRestriction")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRecentTattooOrPiercing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RhFactor")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("Donors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Age = 30,
                            AuthUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BloodGroup = "O",
                            City = "Buenos Aires",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Donante",
                            Gender = 1,
                            HasGuardianAuthorization = true,
                            HasMedicalRestriction = false,
                            HasRecentTattooOrPiercing = false,
                            IsDeleted = false,
                            IsHealthy = true,
                            IsPregnant = false,
                            LastName = "Demo",
                            PhoneNumber = "+5491155550101",
                            Points = 0,
                            Province = "Buenos Aires",
                            RhFactor = "Positive",
                            Street = "Av. Corrientes 1234",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 75m
                        },
                        new
                        {
                            Id = new Guid("d0000000-d000-d000-d000-d00000000001"),
                            Age = 25,
                            AuthUserId = new Guid("f9faea36-22f2-42dc-934c-fc5910baa012"),
                            BloodGroup = "A",
                            City = "Buenos Aires",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Test",
                            Gender = 2,
                            HasGuardianAuthorization = true,
                            HasMedicalRestriction = false,
                            HasRecentTattooOrPiercing = false,
                            IsDeleted = false,
                            IsHealthy = true,
                            IsPregnant = false,
                            LastName = "Donor",
                            PhoneNumber = "+5491155550102",
                            Points = 50,
                            Province = "Buenos Aires",
                            RhFactor = "Positive",
                            Street = "Av. Santa Fe 1234",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 65m
                        });
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.DonorBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("DonorId", "BadgeId")
                        .IsUnique();

                    b.ToTable("DonorBadges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-b000-b000-b000-b00000000001"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BadgeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            DonorId = new Guid("d0000000-d000-d000-d000-d00000000001"),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.ReliabilityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId")
                        .IsUnique();

                    b.ToTable("ReliabilityScores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DonorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            LastCalculatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Score = 100
                        });
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.Donation", b =>
                {
                    b.HasOne("Donnum.DonorService.Domain.Entities.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.DonationRequestParticipation", b =>
                {
                    b.HasOne("Donnum.DonorService.Domain.Entities.Donor", "Donor")
                        .WithMany("DonationRequestParticipations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.Donor", b =>
                {
                    b.OwnsOne("Donnum.DonorService.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("DonorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(10, 8)
                                .HasColumnType("decimal(10,8)");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(11, 8)
                                .HasColumnType("decimal(11,8)");

                            b1.HasKey("DonorId");

                            b1.ToTable("Donors");

                            b1.WithOwner()
                                .HasForeignKey("DonorId");

                            b1.HasData(
                                new
                                {
                                    DonorId = new Guid("11111111-1111-1111-1111-111111111111"),
                                    Latitude = -34.6037m,
                                    Longitude = -58.3816m
                                },
                                new
                                {
                                    DonorId = new Guid("d0000000-d000-d000-d000-d00000000001"),
                                    Latitude = -34.6137m,
                                    Longitude = -58.3916m
                                });
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.DonorBadge", b =>
                {
                    b.HasOne("Donnum.DonorService.Domain.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Donnum.DonorService.Domain.Entities.Donor", "Donor")
                        .WithMany("DonorBadges")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.ReliabilityScore", b =>
                {
                    b.HasOne("Donnum.DonorService.Domain.Entities.Donor", "Donor")
                        .WithOne("ReliabilityScore")
                        .HasForeignKey("Donnum.DonorService.Domain.Entities.ReliabilityScore", "DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Donnum.DonorService.Domain.Entities.Donor", b =>
                {
                    b.Navigation("DonationRequestParticipations");

                    b.Navigation("Donations");

                    b.Navigation("DonorBadges");

                    b.Navigation("ReliabilityScore");
                });
#pragma warning restore 612, 618
        }
    }
}
